# Assignment 3

In [1]:
import pandas as pd

In [3]:
data = {
    'Date':pd.date_range(start='2025-01-01',end='2025-01-10', freq='D'),
    'Sales':[150,250,140,180,230,450,850,950,800,600]
}
df = pd.DataFrame(data)

df

        Date  Sales
0 2025-01-01    150
1 2025-01-02    250
2 2025-01-03    140
3 2025-01-04    180
4 2025-01-05    230
5 2025-01-06    450
6 2025-01-07    850
7 2025-01-08    950
8 2025-01-09    800
9 2025-01-10    600

In [4]:
df['3 Days Moving avg'] = df['Sales'].rolling(window=3).mean()
df

        Date  Sales  3 Days Moving avg
0 2025-01-01    150                NaN
1 2025-01-02    250                NaN
2 2025-01-03    140         180.000000
3 2025-01-04    180         190.000000
4 2025-01-05    230         183.333333
5 2025-01-06    450         286.666667
6 2025-01-07    850         510.000000
7 2025-01-08    950         750.000000
8 2025-01-09    800         866.666667
9 2025-01-10    600         783.333333

# 🚀 Task 2: Time Shifting Challenge
👉 Using the same dataframe (df you created just now):

🔵 Create a new column called 'Yesterday Sales'
🔵 In this column, shift the 'Sales' data by 1 day backward (means ➡️ today's "Yesterday Sales" should be yesterday's actual Sales)

In [5]:
df['Yesterday Sales'] = df['Sales'].shift(1)
df

        Date  Sales  3 Days Moving avg  Yesterday Sales
0 2025-01-01    150                NaN              NaN
1 2025-01-02    250                NaN            150.0
2 2025-01-03    140         180.000000            250.0
3 2025-01-04    180         190.000000            140.0
4 2025-01-05    230         183.333333            180.0
5 2025-01-06    450         286.666667            230.0
6 2025-01-07    850         510.000000            450.0
7 2025-01-08    950         750.000000            850.0
8 2025-01-09    800         866.666667            950.0
9 2025-01-10    600         783.333333            800.0

# ✅ Task 3: Weekly Sales Summary
You have daily sales data. Now your boss wants to see total sales per week to understand how business is doing weekly.

In [13]:
df.resample('W',on='Date').sum()

            Sales  3 Days Moving avg  Yesterday Sales
Date
2025-01-05    950         553.333333            720.0
2025-01-12   3650        3196.666667           3280.0

In [1]:
import pandas as pd

data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Finance', 'Finance'],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Salary': [50000, 52000, 60000, 61000, 70000, 72000],
    'Employee': ['E1', 'E2', 'E3', 'E4', 'E5', 'E6']
}
df = pd.DataFrame(data)

In [2]:
df.groupby('Department')['Salary'].mean()

Department
Finance    71000.0
HR         51000.0
IT         60500.0
Name: Salary, dtype: float64

In [4]:
df.pivot_table(index='Department',columns='Gender',values='Salary', aggfunc='mean', fill_value=0)

Gender       Female     Male
Department
Finance     72000.0  70000.0
HR          52000.0  50000.0
IT          61000.0  60000.0

In [9]:
pd.crosstab(index=df['Department'], columns=df['Gender'], values=df['Employee'], aggfunc='count')

Gender      Female  Male
Department
Finance          1     1
HR               1     1
IT               1     1

In [10]:
df_sales = pd.DataFrame({
    'Date': pd.date_range(start='2025-01-01', periods=10, freq='D'),
    'Sales': [150,250,140,180,230,450,850,950,800,600]
})
df_sales

        Date  Sales
0 2025-01-01    150
1 2025-01-02    250
2 2025-01-03    140
3 2025-01-04    180
4 2025-01-05    230
5 2025-01-06    450
6 2025-01-07    850
7 2025-01-08    950
8 2025-01-09    800
9 2025-01-10    600

In [16]:
df_sales['3 days moving avg'] = df_sales['Sales'].rolling(window=3).mean()
df_sales

        Date  Sales  3 days moving avg
0 2025-01-01    150                NaN
1 2025-01-02    250                NaN
2 2025-01-03    140         180.000000
3 2025-01-04    180         190.000000
4 2025-01-05    230         183.333333
5 2025-01-06    450         286.666667
6 2025-01-07    850         510.000000
7 2025-01-08    950         750.000000
8 2025-01-09    800         866.666667
9 2025-01-10    600         783.333333

In [17]:
df_sales['Yesterday Sales'] = df_sales['Sales'].shift(1)

In [18]:
df_sales

        Date  Sales  3 days moving avg  Yesterday Sales
0 2025-01-01    150                NaN              NaN
1 2025-01-02    250                NaN            150.0
2 2025-01-03    140         180.000000            250.0
3 2025-01-04    180         190.000000            140.0
4 2025-01-05    230         183.333333            180.0
5 2025-01-06    450         286.666667            230.0
6 2025-01-07    850         510.000000            450.0
7 2025-01-08    950         750.000000            850.0
8 2025-01-09    800         866.666667            950.0
9 2025-01-10    600         783.333333            800.0

In [22]:
df_resampled = df_sales.resample('W', on='Date').sum()

In [23]:
df_resampled

            Sales  3 days moving avg  Yesterday Sales
Date
2025-01-05    950         553.333333            720.0
2025-01-12   3650        3196.666667           3280.0