# ASSIGNMENT |

# Create a Pandas Series from a list of your 5 favorite movie names.

In [1]:
import pandas as pd

In [5]:
list1 = ['Inception ','Interstellar','Gladiator','Dangal','3 Idiots']

series = pd.Series(list1)
series

0      Inception
1    Interstellar
2       Gladiator
3          Dangal
4        3 Idiots
dtype: object

# ✅ Task 2:
 Create a DataFrame of 4 friends with the following columns:

In [8]:
friends = {
    "Name":['Rajeev','Ravi','Shahank','Himesh'],
    'Age':[25,19,30,45],
    'City':['Gurgaon','Delhi','Mumbai','Dehradun']
}

df = pd.DataFrame(friends, index = ['A','B','C','D'])
df

      Name  Age      City
A   Rajeev   25   Gurgaon
B     Ravi   19     Delhi
C  Shahank   30    Mumbai
D   Himesh   45  Dehradun

# 🚀 Task 3:
From the DataFrame you just created, do the following:

1. Select and display only the Name and City columns.

2. Access the data for index 'C' using .loc.

3. Get the Age of the friend at index 'B' using .loc.

In [11]:
df[["Name",'City']]

      Name      City
A   Rajeev   Gurgaon
B     Ravi     Delhi
C  Shahank    Mumbai
D   Himesh  Dehradun

In [15]:
df.loc["C"]

Name    Shahank
Age          30
City     Mumbai
Name: C, dtype: object

In [16]:
df.loc["B",'Age']

np.int64(19)

# 🔥 Task 4: Filtering Data
From your friends DataFrame, do the following:

Filter and show the friends whose age is greater than 25.

Filter and show the friends who live in Delhi.

Filter and show the friends whose Age is greater than 20 and City is not Mumbai.

In [17]:
df[df['Age']>25]

      Name  Age      City
C  Shahank   30    Mumbai
D   Himesh   45  Dehradun

In [18]:
df[df['City']=="Delhi"]

   Name  Age   City
B  Ravi   19  Delhi

In [23]:
df[(df['Age']>20) & (df['City']!= "Mumbai")]

     Name  Age      City
A  Rajeev   25   Gurgaon
D  Himesh   45  Dehradun

# 🚀 Task 5: Handling Missing Values
Create a new DataFrame with some missing values (use NaN).

Use the .isnull() function to find which values are missing.

Use .fillna() to replace missing values with "Unknown" for one column and the mean value of the column for another.

Drop any rows that have missing values using .dropna().

In [26]:
import numpy as np

In [28]:
friends2 = {
    "Name": ['Rajeev', np.nan, 'Shahank', np.nan],
    'Age': [25, np.nan, 30, np.nan],
    'City': ['Gurgaon', np.nan, 'Mumbai', np.nan]
}

df2 = pd.DataFrame(friends2)
df2

      Name   Age     City
0   Rajeev  25.0  Gurgaon
1      NaN   NaN      NaN
2  Shahank  30.0   Mumbai
3      NaN   NaN      NaN

In [29]:
df2.isnull

<bound method DataFrame.isnull of       Name   Age     City
0   Rajeev  25.0  Gurgaon
1      NaN   NaN      NaN
2  Shahank  30.0   Mumbai
3      NaN   NaN      NaN>

In [32]:
df2['Name'].fillna("Unknown" , inplace=True)
df2['Age'].fillna(df2['Age'].mean(),inplace=True)

C:\Users\Rajeev\AppData\Local\Temp\ipykernel_13356\2601339876.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Name'].fillna("Unknown" , inplace=True)
C:\Users\Rajeev\AppData\Local\Temp\ipykernel_13356\2601339876.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Age'].fillna(df2['Age'].mean(),inplace=True)

In [33]:
df2

      Name   Age     City
0   Rajeev  25.0  Gurgaon
1  Unknown  27.5      NaN
2  Shahank  30.0   Mumbai
3  Unknown  27.5      NaN

In [37]:
df2.dropna(axis=1)

      Name   Age
0   Rajeev  25.0
1  Unknown  27.5
2  Shahank  30.0
3  Unknown  27.5

In [38]:
df2.dropna()

      Name   Age     City
0   Rajeev  25.0  Gurgaon
2  Shahank  30.0   Mumbai

# ✅ Task 6: Filtering data using loc and iloc
Use the following dataset:

In [2]:
data = {
    "Name": ["Rajeev", "Ravi", "Shahank", "Himesh"],
    "Age": [25, 19, 30, 45],
    "City": ["Gurgaon", "Delhi", "Mumbai", "Dehradun"]
}

df = pd.DataFrame(data, index=["A", "B", "C", "D"])

In [3]:
df.loc['C']

Name    Shahank
Age          30
City     Mumbai
Name: C, dtype: object

In [4]:
df.iloc[1]

Name     Ravi
Age        19
City    Delhi
Name: B, dtype: object

In [5]:
df.iloc[[0,1],[0,2]]

     Name     City
A  Rajeev  Gurgaon
B    Ravi    Delhi

In [6]:
df.loc[df['Age']>20]

      Name  Age      City
A   Rajeev   25   Gurgaon
C  Shahank   30    Mumbai
D   Himesh   45  Dehradun

# ✅ Task 7: String operations in columns
Use this DataFrame:

In [7]:
data = {
    "Name": [" Rajeev ", "RAHUL", "Ravi-Kumar", "Meena"],
    "City": ["delhi", " MUMBAI", "Pune", "chennai"]
}

df = pd.DataFrame(data)

In [9]:
df['Name'] = df['Name'].str.strip()
df

         Name     City
0      Rajeev    delhi
1       RAHUL   MUMBAI
2  Ravi-Kumar     Pune
3       Meena  chennai

In [11]:
df['Name']= df['Name'].str.lower()
df

         Name     City
0      rajeev    delhi
1       rahul   MUMBAI
2  ravi-kumar     Pune
3       meena  chennai

In [12]:
df['Name']= df['Name'].str.replace('-'," ")
df

         Name     City
0      rajeev    delhi
1       rahul   MUMBAI
2  ravi kumar     Pune
3       meena  chennai

In [14]:
df['City']= df['City'].str.upper().str.strip()
df

         Name     City
0      rajeev    DELHI
1       rahul   MUMBAI
2  ravi kumar     PUNE
3       meena  CHENNAI

In [20]:
df.rename(columns={'Name':'Full Name'}, inplace=True)
df

    Full Name     City
0      rajeev    DELHI
1       rahul   MUMBAI
2  ravi kumar     PUNE
3       meena  CHENNAI

# ✅ Task 8: Handling missing values and cleaning duplicates
Use this dataset:

In [21]:
data = {
    "Name": ["Rajeev", None, "Rajeev", "Meena"],
    "Age": [25, None, 25, 30],
    "City": ["Delhi", None, "Delhi", "Pune"]
}

df = pd.DataFrame(data)

In [22]:
df

     Name   Age   City
0  Rajeev  25.0  Delhi
1    None   NaN   None
2  Rajeev  25.0  Delhi
3   Meena  30.0   Pune

In [23]:
df['Name'].fillna('Unknown')

0     Rajeev
1    Unknown
2     Rajeev
3      Meena
Name: Name, dtype: object

In [24]:
df['Age'].fillna(df['Age'].mean())

0    25.000000
1    26.666667
2    25.000000
3    30.000000
Name: Age, dtype: float64

In [25]:
df.drop_duplicates()

     Name   Age   City
0  Rajeev  25.0  Delhi
1    None   NaN   None
3   Meena  30.0   Pune

In [32]:
df.rename(columns={'City':'Location'},inplace=True)
df

     Name   Age Loocation
0  Rajeev  25.0     Delhi
1    None   NaN      None
2  Rajeev  25.0     Delhi
3   Meena  30.0      Pune

In [33]:
df

     Name   Age Loocation
0  Rajeev  25.0     Delhi
1    None   NaN      None
2  Rajeev  25.0     Delhi
3   Meena  30.0      Pune

# 🚀 Task 9: Working with Indexing and Filtering
Using this dataset:

In [34]:
students = {
    'Name': ['Rajeev', 'Sneha', 'Karan', 'Divya'],
    'Score': [88, 92, 45, 76],
    'Grade': ['B', 'A', 'D', 'C']
}

df = pd.DataFrame(students, index=['S1', 'S2', 'S3', 'S4'])

In [35]:
df

      Name  Score Grade
S1  Rajeev     88     B
S2   Sneha     92     A
S3   Karan     45     D
S4   Divya     76     C

In [36]:
df.loc['S2']

Name     Sneha
Score       92
Grade        A
Name: S2, dtype: object

In [37]:
df.iloc[1]

Name     Sneha
Score       92
Grade        A
Name: S2, dtype: object

In [40]:
df.loc[['S1','S3'],['Name','Grade']]

      Name Grade
S1  Rajeev     B
S3   Karan     D

In [41]:
df[df['Score']>80]

      Name  Score Grade
S1  Rajeev     88     B
S2   Sneha     92     A

# 🚀 Task 10: Sorting and Ranking
Use the same students DataFrame:

In [42]:
students = {
    'Name': ['Rajeev', 'Sneha', 'Karan', 'Divya'],
    'Score': [88, 92, 45, 76],
    'Grade': ['B', 'A', 'D', 'C']
}
df = pd.DataFrame(students, index=['S1', 'S2', 'S3', 'S4'])

In [47]:
df.sort_values(by=['Score'])

      Name  Score Grade
S3   Karan     45     D
S4   Divya     76     C
S1  Rajeev     88     B
S2   Sneha     92     A

In [45]:
df

      Name  Score Grade
S1  Rajeev     88     B
S2   Sneha     92     A
S3   Karan     45     D
S4   Divya     76     C

In [48]:
df.sort_values(by='Name',ascending=True)

      Name  Score Grade
S4   Divya     76     C
S3   Karan     45     D
S1  Rajeev     88     B
S2   Sneha     92     A

In [52]:
df['Rank']= df['Score'].rank(ascending=False,method='min').astype(int)
df

      Name  Score Grade  Rank
S1  Rajeev     88     B     2
S2   Sneha     92     A     1
S3   Karan     45     D     4
S4   Divya     76     C     3

# ✅ Task 11: Grouping and Aggregation
Use the following DataFrame:

In [53]:
data = {
    "Department": ["Sales", "HR", "Sales", "HR", "Finance", "Sales", "Finance"],
    "Name": ["Raj", "Ravi", "Kiran", "Meena", "Ali", "Sneha", "Tom"],
    "Salary": [50000, 45000, 55000, 47000, 60000, 52000, 62000]
}

df = pd.DataFrame(data)

In [55]:
df.groupby('Department')['Salary'].mean()

Department
Finance    61000.000000
HR         46000.000000
Sales      52333.333333
Name: Salary, dtype: float64

In [56]:
df.groupby('Department')['Salary'].max()

Department
Finance    62000
HR         47000
Sales      55000
Name: Salary, dtype: int64

In [61]:
avg_salary = df.groupby('Department')['Salary'].mean().sort_values(ascending=False)
avg_salary

Department
Finance    61000.000000
Sales      52333.333333
HR         46000.000000
Name: Salary, dtype: float64

# 🧠 Task 12:
You’re given a DataFrame with sales data:

In [62]:
data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Sales': [250, 150, 200, 300, 275, 180, 220, 310],
    'Product': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B']
}

df = pd.DataFrame(data)

# Now do the following:
Group the data by Region and calculate the total Sales.

Group by Product and get the average sales for each product.

Group by both Region and Product and calculate the sum of sales.

In [63]:
df.groupby('Region')['Sales'].sum()

Region
East     420
North    525
South    330
West     610
Name: Sales, dtype: int64

In [64]:
df.groupby('Product')['Sales'].mean()

Product
A    236.25
B    235.00
Name: Sales, dtype: float64

In [65]:
df.groupby(['Region','Product'])['Sales'].sum()

Region  Product
East    A          420
North   A          525
South   B          330
West    B          610
Name: Sales, dtype: int64

# 🧠 Task 13:
You’re given a DataFrame with sales data:

In [3]:
data = {
    'Employee': ['John', 'Jane', 'Sam', 'Mike', 'Alice'],
    'Department': ['HR', 'Finance', 'HR', 'Finance', 'HR'],
    'Salary': [50000, 60000, 55000, 65000, 52000],
    'Years_of_Experience': [5, 7, 6, 8, 4]
}

df = pd.DataFrame(data)

In [ ]:
df['Salary_Increment']=