# Assignment 2

In [1]:
import pandas as pd

data = {
    'Employee': ['John', 'Alice', 'Bob', 'Daisy', 'Ethan', 'Fiona'],
    'Department': ['HR', 'Finance', 'IT', 'Finance', 'HR', 'IT'],
    'Salary': [50000, 60000, 55000, 62000, 52000, 58000],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female']
}

df = pd.DataFrame(data)

In [2]:
df

  Employee Department  Salary  Gender
0     John         HR   50000    Male
1    Alice    Finance   60000  Female
2      Bob         IT   55000    Male
3    Daisy    Finance   62000  Female
4    Ethan         HR   52000    Male
5    Fiona         IT   58000  Female

# 🎯 Your Task:
Use groupby() to find:

Average salary for each Department

In [3]:
df.groupby('Department')['Salary'].mean()

Department
Finance    61000.0
HR         51000.0
IT         56500.0
Name: Salary, dtype: float64

# 🎯 Your Task:
Use groupby() to find:

Total salary and count of employees for each Department and Gender combination.

(Hint: Use agg() to apply multiple functions.)

In [5]:
df.groupby(['Department','Gender']).agg({
    'Salary':'sum',
    'Employee':'count'
})

                   Salary  Employee
Department Gender
Finance    Female  122000         2
HR         Male    102000         2
IT         Female   58000         1
           Male     55000         1

# 🎯 Your Task:
Create a pivot table that shows the average salary for each Department and Gender.

(Hint: use pivot_table() with index, columns, and values.)

In [10]:
pivot = df.pivot_table(index='Department', columns='Gender',values='Salary', aggfunc='mean', fill_value=0)
pivot

Gender       Female     Male
Department
Finance     61000.0      0.0
HR              0.0  51000.0
IT          58000.0  55000.0

# 📊 Pivot Table — Task 2
🎯 Your Task:
Create a pivot table that shows the total salary for each combination of Department and Gender.

This time, instead of average, calculate the sum.
(Use the same DataFrame.)

In [13]:
pivot = df.pivot_table(index='Department', columns='Gender',values='Salary', aggfunc='sum', fill_value=0)
pivot

Gender      Female    Male
Department
Finance     122000       0
HR               0  102000
IT           58000   55000

# 📊 Crosstab — Task 1
🎯 Your Task:
Create a crosstab that shows the count of employees by Department and Gender.

Use pd.crosstab() and just count how many employees are there in each combo.
Simple and clean.

In [14]:
df

  Employee Department  Salary  Gender
0     John         HR   50000    Male
1    Alice    Finance   60000  Female
2      Bob         IT   55000    Male
3    Daisy    Finance   62000  Female
4    Ethan         HR   52000    Male
5    Fiona         IT   58000  Female

In [20]:
crosstab = pd.crosstab(index=df['Department'],columns=df['Gender'])
crosstab

Gender      Female  Male
Department
Finance          2     0
HR               0     2
IT               1     1

# 📌 Crosstab Task 2:
Using the same df, create a crosstab that shows the total Salary of employees by Department and Gender.

Hint: You’ll need to use values= and aggfunc= here 😉

In [23]:
crosstab = pd.crosstab(index=df['Department'],columns=df['Gender'],values=df['Salary'],aggfunc='sum')
crosstab

Gender        Female      Male
Department
Finance     122000.0       NaN
HR               NaN  102000.0
IT           58000.0   55000.0