# 10. Pivot Table & Crosstab

In [1]:
import pandas as pd

# Pivot Table Basics
A pivot table is a powerful tool for summarizing data. It allows you to transform data and aggregate it, making it easier to analyze trends and patterns. In Pandas, you can create a pivot table using the pivot_table() function.

# Syntax

df.pivot_table(values, index, columns, aggfunc)

# Where:

values: The column you want to aggregate.

index: The column(s) to group by (rows in the pivot table).

columns: The column(s) to use as columns in the pivot table.

aggfunc: The aggregation function to apply (e.g., mean, sum, count, etc.).

In [8]:

data = {
    'Department': ['HR', 'Finance', 'HR', 'Finance', 'HR', 'Finance'],
    'Gender': ['M', 'F', 'M', 'F', 'M', 'M'],
    'Salary': [50000, None, 55000, 65000, 52000, 67000],
    'Experience': [5, 7, 6, 8, 4, 10]
}

df = pd.DataFrame(data)
df

  Department Gender   Salary  Experience
0         HR      M  50000.0           5
1    Finance      F      NaN           7
2         HR      M  55000.0           6
3    Finance      F  65000.0           8
4         HR      M  52000.0           4
5    Finance      M  67000.0          10

In [4]:
pivot = df.pivot_table(values='Salary',index='Department',aggfunc='mean')
pivot

                  Salary
Department
Finance     64000.000000
HR          52333.333333

In [10]:
pivot = df.pivot_table(values=['Salary','Experience'],index='Department')
pivot

            Experience        Salary
Department
Finance       8.333333  66000.000000
HR            5.000000  52333.333333

# Handling Missing Data in Pivot Tables
By default, Pandas excludes NaN values when creating a pivot table. However, you can control how missing values are handled using the fill_value argument. For example:

In [9]:
pivot = df.pivot_table(values='Salary', index='Department', aggfunc='mean', fill_value=0)
print(pivot)

                  Salary
Department
Finance     66000.000000
HR          52333.333333

# Crosstab: Similar to Pivot Table, but for Categorical Data
A crosstab is a cross-tabulation of data, similar to a pivot table but used for categorical data. It helps you to quickly analyze the relationship between two categorical variables.

# Syntax:
pd.crosstab(index, columns, values=None, aggfunc=None)

In [11]:
crosstab= pd.crosstab(df['Department'],df['Gender'])
crosstab

Gender      F  M
Department
Finance     2  1
HR          0  3

In [13]:
crosstab = pd.crosstab(df['Department'], df['Gender'], values=df['Salary'], aggfunc='mean')
crosstab

Gender            F             M
Department
Finance     65000.0  67000.000000
HR              NaN  52333.333333