# Chapter 4 | Data Selection, Filtering, and Indexing in Pandas

In [2]:
import pandas as pd

In [3]:
ins_data= pd.read_csv("C:\Data Analytics\Python\Pandas\insurance.csv")

In [4]:
ins_data.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

# get Random Rows

In [7]:
ins_data.sample()

     age   sex   bmi  children smoker     region  expenses
150   35  male  24.1         1     no  northwest   5125.22

# Set a Column as Index

In [9]:
ins_data.set_index('sex')

        age   bmi  children smoker     region  expenses
sex
female   19  27.9         0    yes  southwest  16884.92
male     18  33.8         1     no  southeast   1725.55
male     28  33.0         3     no  southeast   4449.46
male     33  22.7         0     no  northwest  21984.47
male     32  28.9         0     no  northwest   3866.86
...     ...   ...       ...    ...        ...       ...
male     50  31.0         3     no  northwest  10600.55
female   18  31.9         0     no  northeast   2205.98
female   18  36.9         0     no  southeast   1629.83
female   21  25.8         0     no  southwest   2007.95
female   61  29.1         0    yes  northwest  29141.36

[1338 rows x 6 columns]

In [11]:
ins_data.index

RangeIndex(start=0, stop=1338, step=1)

In [12]:
ins_data.set_index('age', inplace=True)

In [13]:
ins_data.head()

        sex   bmi  children smoker     region  expenses
age
19   female  27.9         0    yes  southwest  16884.92
18     male  33.8         1     no  southeast   1725.55
28     male  33.0         3     no  southeast   4449.46
33     male  22.7         0     no  northwest  21984.47
32     male  28.9         0     no  northwest   3866.86

#  Moves index back to column,

In [15]:
ins_data.reset_index()

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

# Sorting Values

# 👉 By Column Values

In [16]:
ins_data.sort_values('age')

        sex   bmi  children smoker     region  expenses
age
18     male  31.7         2    yes  southeast  34303.17
18   female  26.3         0     no  northeast   2198.19
18     male  23.3         1     no  southeast   1711.03
18   female  29.2         0     no  northeast   7323.73
18     male  53.1         0     no  southeast   1163.46
..      ...   ...       ...    ...        ...       ...
64   female  39.1         3     no  southeast  16085.13
64     male  40.5         0     no  southeast  13831.12
64     male  37.0         2    yes  southeast  49577.66
64   female  36.0         0     no  southeast  14313.85
64   female  39.7         0     no  southwest  14319.03

[1338 rows x 6 columns]

In [17]:
ins_data.sort_values('age',ascending=False)

        sex   bmi  children smoker     region  expenses
age
64     male  23.8         0    yes  southeast  26926.51
64     male  37.0         2    yes  southeast  49577.66
64     male  37.9         0     no  northwest  14210.54
64   female  39.7         0     no  southwest  14319.03
64   female  31.8         2     no  northeast  16069.08
..      ...   ...       ...    ...        ...       ...
18     male  25.2         0    yes  northeast  15518.18
18   female  36.9         0    yes  southeast  36149.48
18   female  38.7         2     no  northeast   3393.36
18   female  35.6         0     no  northeast   2211.13
18     male  37.3         0     no  southeast   1141.45

[1338 rows x 6 columns]