#  Chapter 9: GroupBy in Pandas - Master Level Start

In [1]:
import pandas as pd

# 🧠 What is groupby() in Pandas?

The groupby() method is used to split the data into groups based on some criteria, apply a function (like mean, sum, etc.), and combine the results.

This is also called:
Split → Apply → Combine

# 💡 Real-life Example:
Imagine a company has 100 employees across departments (like HR, Finance, IT), and you want to find the average salary in each department. groupby() makes that super easy.

# ✅ Basic Syntax:

# 💡 Advanced GroupBy - GroupBy with Multiple Columns

df.groupby('column_name').agg({
    'column_to_aggregate1': 'agg_function1',
    'column_to_aggregate2': 'agg_function2',
    # more columns and functions
})

In [4]:

data = {
    'Department': ['HR', 'IT', 'Finance', 'HR', 'IT', 'Finance', 'HR'],
    'Salary': [50000, 70000, 60000, 52000, 72000, 61000, 51000],
    'Experience': [3, 5, 6, 4, 7, 9, 2]
}

df = pd.DataFrame(data)
df

  Department  Salary  Experience
0         HR   50000           3
1         IT   70000           5
2    Finance   60000           6
3         HR   52000           4
4         IT   72000           7
5    Finance   61000           9
6         HR   51000           2

In [6]:
df.groupby('Department').agg({
    'Salary':['mean','sum','max'],
    'Experience':['min','max']
})

             Salary                Experience
               mean     sum    max        min max
Department
Finance     60500.0  121000  61000          6   9
HR          51000.0  153000  52000          2   4
IT          71000.0  142000  72000          5   7

In [7]:
data = {
    'Department': ['HR', 'IT', 'Finance', 'HR', 'IT', 'Finance', 'HR', 'IT'],
    'Gender': ['M', 'M', 'F', 'F', 'M', 'F', 'M', 'F'],
    'Salary': [50000, 70000, 60000, 52000, 72000, 61000, 51000, 74000],
    'Experience': [3, 5, 6, 4, 7, 9, 2, 8]
}

df = pd.DataFrame(data)
df

  Department Gender  Salary  Experience
0         HR      M   50000           3
1         IT      M   70000           5
2    Finance      F   60000           6
3         HR      F   52000           4
4         IT      M   72000           7
5    Finance      F   61000           9
6         HR      M   51000           2
7         IT      F   74000           8

In [8]:
df.groupby(['Department','Gender']).agg({
    'Salary':'mean',
    'Experience':'sum'
})

                    Salary  Experience
Department Gender
Finance    F       60500.0          15
HR         F       52000.0           4
           M       50500.0           5
IT         F       74000.0           8
           M       71000.0          12

In [9]:
df.groupby('Gender').agg({
    'Experience': 'sum'
})

        Experience
Gender
F               27
M               17

In [10]:
df.groupby(['Department','Gender']).agg({
    'Salary':'mean',
    'Experience':'sum'
})

                    Salary  Experience
Department Gender
Finance    F       60500.0          15
HR         F       52000.0           4
           M       50500.0           5
IT         F       74000.0           8
           M       71000.0          12