# Working with Missing Data (NaN) in Pandas

-- In real-world data, sometimes some values are missing.
-- We call those NaN (Not a Number) in Pandas.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Name': ['Rajeev', 'Rahul', 'Rakesh', 'Mukesh'],
    'Age': [25, np.nan, 35, 40],
    'City': ['Delhi', 'Mumbai', np.nan, 'Chennai']
}

In [16]:
df = pd.DataFrame(data)
df

     Name   Age     City
0  Rajeev  25.0    Delhi
1   Rahul   NaN   Mumbai
2  Rakesh  35.0      NaN
3  Mukesh  40.0  Chennai

# 1️⃣ Check where NaN exists

In [4]:
df.isnull()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

# 2️⃣ Count total missing values

-- 👉 Tells how many missing values are in each column.

In [5]:
df.isnull().sum()

Name    0
Age     1
City    1
dtype: int64

# ✅ 1. Remove Missing Data

-- 👉 Drop rows with missing values:

In [8]:
df.dropna(inplace=True)
df

     Name   Age     City
0  Rajeev  25.0    Delhi
3  Mukesh  40.0  Chennai

In [10]:
df

     Name   Age     City
0  Rajeev  25.0    Delhi
1   Rahul   NaN   Mumbai
2  Rakesh  35.0      NaN
3  Mukesh  40.0  Chennai

# ✅ 2. Replace Missing Data

In [12]:
df.fillna(0)

     Name   Age     City
0  Rajeev  25.0    Delhi
1   Rahul   0.0   Mumbai
2  Rakesh  35.0        0
3  Mukesh  40.0  Chennai

# 👉 Replace NaN with mean, median, or mode

In [13]:
df['Age'].fillna(df['Age'].mean())

0    25.000000
1    33.333333
2    35.000000
3    40.000000
Name: Age, dtype: float64

# 👉 Forward fill (copy previous value)

In [15]:
df.fillna(method='ffill', inplace=True)
df

C:\Users\Rajeev\AppData\Local\Temp\ipykernel_25000\3303779087.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

     Name   Age     City
0  Rajeev  25.0    Delhi
1   Rahul  25.0   Mumbai
2  Rakesh  35.0   Mumbai
3  Mukesh  40.0  Chennai

In [17]:
df

     Name   Age     City
0  Rajeev  25.0    Delhi
1   Rahul   NaN   Mumbai
2  Rakesh  35.0      NaN
3  Mukesh  40.0  Chennai

In [18]:
df.ffill()

     Name   Age     City
0  Rajeev  25.0    Delhi
1   Rahul  25.0   Mumbai
2  Rakesh  35.0   Mumbai
3  Mukesh  40.0  Chennai

In [19]:
df.bfill()

     Name   Age     City
0  Rajeev  25.0    Delhi
1   Rahul  35.0   Mumbai
2  Rakesh  35.0  Chennai
3  Mukesh  40.0  Chennai

# ✅ 3. Check If Any Missing Data Exists

In [20]:
df.isnull().values.any()

np.True_