# Chapter 7 - Data Cleaning (The Real-World Savior)

In [1]:
import pandas as pd

In the real world, data is never clean. You’ll face:

Missing values 😱

Wrong data types 😤

Duplicates 😬

Inconsistent formatting 😵

Garbage values 🗑️

This chapter teaches you how to clean your data like a pro 🧠

# 🔷 1. Handling Missing Data (NaN)

In [2]:
df = pd.read_csv("C:\Data Analytics\EXCEL ADVANCE\PROJECTS\Project -2 Hospital Room Analysis\Hospital Emergency Room Data.csv")

In [3]:
df.head()

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Admission Flag.1
0,145-39-5406,20-03-2024 08:47,H,Glasspool,M,69,White,NaN,False,10.0,39,False
1,316-34-3057,15-06-2024 11:29,X,Methuen,M,4,Native American/Alaska Native,NaN,True,NaN,27,True
2,897-46-3852,20-06-2024 09:13,P,Schubuser,F,56,African American,General Practice,True,9.0,55,True
3,358-31-9711,4/2/2024,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,True
4,289-26-0537,4/9/2024,Y,Gionettitti,Male,5,African American,Orthopedics,False,NaN,10,False

# 🟢 Detecting missing values

In [5]:
df.isnull() # # Shows True where data is missing

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Admission Flag.1
0,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,True,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9211,False,False,False,False,False,False,False,False,False,True,False,False
9212,False,False,False,False,False,False,False,True,False,True,False,False
9213,False,False,False,False,False,False,False,True,False,True,False,False
9214,False,False,False,False,False,False,False,False,False,False,False,False
9215,False,False,False,False,False,False,False,False,False,True,False,False

In [6]:
df.notnull()        # Shows True where data is present

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Admission Flag.1
0,True,True,True,True,True,True,True,False,True,True,True,True
1,True,True,True,True,True,True,True,False,True,False,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
9211,True,True,True,True,True,True,True,True,True,False,True,True
9212,True,True,True,True,True,True,True,False,True,False,True,True
9213,True,True,True,True,True,True,True,False,True,False,True,True
9214,True,True,True,True,True,True,True,True,True,True,True,True
9215,True,True,True,True,True,True,True,True,True,False,True,True

# 🟢 Counting missing values

In [7]:
df.isnull().sum() # Count NaN in each column

Patient Id                       0
Patient Admission Date           0
Patient First Inital             0
Patient Last Name                0
Patient Gender                   0
Patient Age                      0
Patient Race                     0
Department Referral           5400
Patient Admission Flag           0
Patient Satisfaction Score    6699
Patient Waittime                 0
Patient Admission Flag.1         0
dtype: int64

# 🟢 Removing missing values

In [28]:
df.dropna(axis = 1,how='all')

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Admission Flag.1
0,145-39-5406,2024-03-20 08:47:00,H,Glasspool,M,69,White,NaN,False,10.0,39,False
1,316-34-3057,2024-06-15 11:29:00,X,Methuen,M,4,Native American/Alaska Native,NaN,True,NaN,27,True
2,897-46-3852,2024-06-20 09:13:00,P,Schubuser,F,56,African American,General Practice,True,9.0,55,True
3,358-31-9711,2024-04-02 00:00:00,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,True
4,289-26-0537,2024-04-09 00:00:00,Y,Gionettitti,Male,5,African American,Orthopedics,False,NaN,10,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9211,313-21-4953,2024-08-28 17:38:00,J,Spradbrow,Male,42,Asian,General Practice,True,NaN,43,True
9212,226-92-3412,2024-06-28 23:12:00,G,Antoniak,Male,19,Asian,NaN,True,NaN,49,True
9213,412-85-3832,2024-05-16 17:06:00,V,Riccardo,Male,14,Asian,NaN,True,NaN,36,True
9214,708-91-2439,2024-05-14 23:43:00,S,Renals,Male,73,Declined to Identify,General Practice,True,1.0,38,True
9215,249-47-9666,2024-01-03 00:00:00,Y,Greep,Male,35,White,General Practice,True,NaN,39,True

In [10]:
df.dropna(axis=1) # Drops columns with NaN

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Patient Admission Flag,Patient Waittime,Patient Admission Flag.1
0,145-39-5406,20-03-2024 08:47,H,Glasspool,M,69,White,False,39,False
1,316-34-3057,15-06-2024 11:29,X,Methuen,M,4,Native American/Alaska Native,True,27,True
2,897-46-3852,20-06-2024 09:13,P,Schubuser,F,56,African American,True,55,True
3,358-31-9711,4/2/2024,U,Titcombe,F,24,Native American/Alaska Native,True,31,True
4,289-26-0537,4/9/2024,Y,Gionettitti,Male,5,African American,False,10,False
...,...,...,...,...,...,...,...,...,...,...
9211,313-21-4953,28-08-2024 17:38,J,Spradbrow,Male,42,Asian,True,43,True
9212,226-92-3412,28-06-2024 23:12,G,Antoniak,Male,19,Asian,True,49,True
9213,412-85-3832,16-05-2024 17:06,V,Riccardo,Male,14,Asian,True,36,True
9214,708-91-2439,14-05-2024 23:43,S,Renals,Male,73,Declined to Identify,True,38,True
9215,249-47-9666,1/3/2024,Y,Greep,Male,35,White,True,39,True

# 🟢 Filling missing values

In [13]:
df.fillna(0) # Replace NaN with 0

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Admission Flag.1
0,145-39-5406,20-03-2024 08:47,H,Glasspool,M,69,White,0,False,10.0,39,False
1,316-34-3057,15-06-2024 11:29,X,Methuen,M,4,Native American/Alaska Native,0,True,0.0,27,True
2,897-46-3852,20-06-2024 09:13,P,Schubuser,F,56,African American,General Practice,True,9.0,55,True
3,358-31-9711,4/2/2024,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,True
4,289-26-0537,4/9/2024,Y,Gionettitti,Male,5,African American,Orthopedics,False,0.0,10,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9211,313-21-4953,28-08-2024 17:38,J,Spradbrow,Male,42,Asian,General Practice,True,0.0,43,True
9212,226-92-3412,28-06-2024 23:12,G,Antoniak,Male,19,Asian,0,True,0.0,49,True
9213,412-85-3832,16-05-2024 17:06,V,Riccardo,Male,14,Asian,0,True,0.0,36,True
9214,708-91-2439,14-05-2024 23:43,S,Renals,Male,73,Declined to Identify,General Practice,True,1.0,38,True
9215,249-47-9666,1/3/2024,Y,Greep,Male,35,White,General Practice,True,0.0,39,True

In [14]:
df.fillna("Unknown") # Replace NaN with a string

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Admission Flag.1
0,145-39-5406,20-03-2024 08:47,H,Glasspool,M,69,White,Unknown,False,10.0,39,False
1,316-34-3057,15-06-2024 11:29,X,Methuen,M,4,Native American/Alaska Native,Unknown,True,Unknown,27,True
2,897-46-3852,20-06-2024 09:13,P,Schubuser,F,56,African American,General Practice,True,9.0,55,True
3,358-31-9711,4/2/2024,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,True
4,289-26-0537,4/9/2024,Y,Gionettitti,Male,5,African American,Orthopedics,False,Unknown,10,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9211,313-21-4953,28-08-2024 17:38,J,Spradbrow,Male,42,Asian,General Practice,True,Unknown,43,True
9212,226-92-3412,28-06-2024 23:12,G,Antoniak,Male,19,Asian,Unknown,True,Unknown,49,True
9213,412-85-3832,16-05-2024 17:06,V,Riccardo,Male,14,Asian,Unknown,True,Unknown,36,True
9214,708-91-2439,14-05-2024 23:43,S,Renals,Male,73,Declined to Identify,General Practice,True,1.0,38,True
9215,249-47-9666,1/3/2024,Y,Greep,Male,35,White,General Practice,True,Unknown,39,True

In [16]:
df.columns

Index(['Patient Id', 'Patient Admission Date', 'Patient First Inital',
       'Patient Last Name', 'Patient Gender', 'Patient Age', 'Patient Race',
       'Department Referral', 'Patient Admission Flag',
       'Patient Satisfaction Score', 'Patient Waittime',
       'Patient Admission Flag.1'],
      dtype='object')

In [18]:
df["Patient Satisfaction Score"].fillna(df['Patient Satisfaction Score'].mean())

0       10.000000
1        4.992054
2        9.000000
3        8.000000
4        4.992054
          ...
9211     4.992054
9212     4.992054
9213     4.992054
9214     1.000000
9215     4.992054
Name: Patient Satisfaction Score, Length: 9216, dtype: float64

# 🔷 2. Fixing Wrong Data Types

Sometimes a column is read as object (string) but should be numeric or datetime.

In [22]:
df.dtypes

Patient Id                     object
Patient Admission Date         object
Patient First Inital           object
Patient Last Name              object
Patient Gender                 object
Patient Age                     int64
Patient Race                   object
Department Referral            object
Patient Admission Flag           bool
Patient Satisfaction Score    float64
Patient Waittime                int64
Patient Admission Flag.1         bool
dtype: object

In [24]:
df['Patient Admission Date'] = pd.to_datetime(df['Patient Admission Date'], format='mixed')

# 🔷 3. Removing Duplicates

# 🧹 Detect and Remove

In [33]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9211    False
9212    False
9213    False
9214    False
9215    False
Length: 9216, dtype: bool

In [34]:
df.drop_duplicates()

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Admission Flag.1
0,145-39-5406,2024-03-20 08:47:00,H,Glasspool,M,69,White,NaN,False,10.0,39,False
1,316-34-3057,2024-06-15 11:29:00,X,Methuen,M,4,Native American/Alaska Native,NaN,True,NaN,27,True
2,897-46-3852,2024-06-20 09:13:00,P,Schubuser,F,56,African American,General Practice,True,9.0,55,True
3,358-31-9711,2024-04-02 00:00:00,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,True
4,289-26-0537,2024-04-09 00:00:00,Y,Gionettitti,Male,5,African American,Orthopedics,False,NaN,10,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9211,313-21-4953,2024-08-28 17:38:00,J,Spradbrow,Male,42,Asian,General Practice,True,NaN,43,True
9212,226-92-3412,2024-06-28 23:12:00,G,Antoniak,Male,19,Asian,NaN,True,NaN,49,True
9213,412-85-3832,2024-05-16 17:06:00,V,Riccardo,Male,14,Asian,NaN,True,NaN,36,True
9214,708-91-2439,2024-05-14 23:43:00,S,Renals,Male,73,Declined to Identify,General Practice,True,1.0,38,True
9215,249-47-9666,2024-01-03 00:00:00,Y,Greep,Male,35,White,General Practice,True,NaN,39,True

# 🔷 4. Replacing Values

In [35]:
df['Patient First Inital'].replace("H","Rajeev Kumar", inplace=True)

C:\Users\Rajeev\AppData\Local\Temp\ipykernel_19144\3852994234.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Patient First Inital'].replace("H","Rajeev Kumar", inplace=True)

In [37]:
df.head()

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Admission Flag.1
0,145-39-5406,2024-03-20 08:47:00,Rajeev Kumar,Glasspool,M,69,White,NaN,False,10.0,39,False
1,316-34-3057,2024-06-15 11:29:00,X,Methuen,M,4,Native American/Alaska Native,NaN,True,NaN,27,True
2,897-46-3852,2024-06-20 09:13:00,P,Schubuser,F,56,African American,General Practice,True,9.0,55,True
3,358-31-9711,2024-04-02 00:00:00,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,True
4,289-26-0537,2024-04-09 00:00:00,Y,Gionettitti,Male,5,African American,Orthopedics,False,NaN,10,False

In [38]:
df['Patient First Inital'].replace({
    "Rajeev Kumar":"Rajeev",
    "X":"Ravi"
}, inplace= True)

C:\Users\Rajeev\AppData\Local\Temp\ipykernel_19144\2191284989.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Patient First Inital'].replace({

In [39]:
df.head()

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Admission Flag.1
0,145-39-5406,2024-03-20 08:47:00,Rajeev,Glasspool,M,69,White,NaN,False,10.0,39,False
1,316-34-3057,2024-06-15 11:29:00,Ravi,Methuen,M,4,Native American/Alaska Native,NaN,True,NaN,27,True
2,897-46-3852,2024-06-20 09:13:00,P,Schubuser,F,56,African American,General Practice,True,9.0,55,True
3,358-31-9711,2024-04-02 00:00:00,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,True
4,289-26-0537,2024-04-09 00:00:00,Y,Gionettitti,Male,5,African American,Orthopedics,False,NaN,10,False

# 🔷 5. String Operations and Cleaning

In [44]:
df["Patient First Inital"] = df["Patient First Inital"].str.strip()
df["Patient Last Name"] = df["Patient Last Name"].str.lower()
df["Department Referral"] = df["Department Referral"].str.upper()
df["Patient Race"] = df["Patient Race"].str.replace("/", "|", regex=False)

df.head()

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Admission Flag.1
0,145-39-5406,2024-03-20 08:47:00,Rajeev,glasspool,M,69,White,NaN,False,10.0,39,False
1,316-34-3057,2024-06-15 11:29:00,Ravi,methuen,M,4,Native American|Alaska Native,NaN,True,NaN,27,True
2,897-46-3852,2024-06-20 09:13:00,P,schubuser,F,56,African American,GENERAL PRACTICE,True,9.0,55,True
3,358-31-9711,2024-04-02 00:00:00,U,titcombe,F,24,Native American|Alaska Native,GENERAL PRACTICE,True,8.0,31,True
4,289-26-0537,2024-04-09 00:00:00,Y,gionettitti,Male,5,African American,ORTHOPEDICS,False,NaN,10,False

# 🔷 6. Renaming Columns

In [45]:
df.rename(columns={'Patient First Inital':"First Name", 'Patient Last Name':"Last Name"},inplace=True)
df.head()

,Patient Id,Patient Admission Date,First Name,Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Admission Flag.1
0,145-39-5406,2024-03-20 08:47:00,Rajeev,glasspool,M,69,White,NaN,False,10.0,39,False
1,316-34-3057,2024-06-15 11:29:00,Ravi,methuen,M,4,Native American|Alaska Native,NaN,True,NaN,27,True
2,897-46-3852,2024-06-20 09:13:00,P,schubuser,F,56,African American,GENERAL PRACTICE,True,9.0,55,True
3,358-31-9711,2024-04-02 00:00:00,U,titcombe,F,24,Native American|Alaska Native,GENERAL PRACTICE,True,8.0,31,True
4,289-26-0537,2024-04-09 00:00:00,Y,gionettitti,Male,5,African American,ORTHOPEDICS,False,NaN,10,False

# 🧪 Real-Life Task for Practice:

In [47]:
data = {
    "Name": ["Rajeev", "Rahul", None, "Rakesh", "Rakesh"],
    "Age": [25, None, 30, 45, 45],
    "Gender": ["M", "F", "M", "M", "M"]
}

df2 = pd.DataFrame(data)

In [48]:
df2.isnull()

    Name    Age  Gender
0  False  False   False
1  False   True   False
2   True  False   False
3  False  False   False
4  False  False   False

In [51]:
df2['Name'].fillna("Unknown" , inplace=True)
df2['Age'].fillna(df2['Age'].mean(),inplace=True)

C:\Users\Rajeev\AppData\Local\Temp\ipykernel_19144\2601339876.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Name'].fillna("Unknown" , inplace=True)
C:\Users\Rajeev\AppData\Local\Temp\ipykernel_19144\2601339876.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Age'].fillna(df2['Age'].mean(),inplace=True)

In [52]:
df2

      Name    Age Gender
0   Rajeev  25.00      M
1    Rahul  36.25      F
2  Unknown  30.00      M
3   Rakesh  45.00      M
4   Rakesh  45.00      M

In [53]:
df2.drop_duplicates()

      Name    Age Gender
0   Rajeev  25.00      M
1    Rahul  36.25      F
2  Unknown  30.00      M
3   Rakesh  45.00      M

In [56]:
df2.rename(columns={"Gender":"Sex"})

      Name    Age Sex
0   Rajeev  25.00   M
1    Rahul  36.25   F
2  Unknown  30.00   M
3   Rakesh  45.00   M
4   Rakesh  45.00   M

In [64]:
# Step 1: Fill missing values in 'Age' column
df2['Age'].fillna(df2['Age'].mean(), inplace=True)

# Step 2: Convert to int safely
df2['Age'] = df2['Age'].astype(int)

In [65]:
df2.dtypes

Name      object
Age        int64
Gender    object
dtype: object