# Pandas Chapter 1

In [1]:
import pandas as pd

# Pandas is a Python library that makes working with structured data (like tables, spreadsheets, CSV files) super easy.

# Data Structure In Pandas

# Series

In [11]:
listA = [1,2,3,4,5,6]
listB = [7,8,9,4,5,6]

In [9]:
series = pd.Series(listA,listB)
series

7    1
8    2
9    3
4    4
5    5
6    6
dtype: int64

# Creating Data Frames

In [17]:
freinds_data = {
    'Name': ["Rajeev","Rahul","Rakesh","Mukesh"],
    "Age": [25,15,45,85],
    "Insured":[True,False,False,True]
}

In [21]:
freind_df = pd.DataFrame(freinds_data,index=['A','B','C','D'])
freind_df

     Name  Age  Insured
A  Rajeev   25     True
B   Rahul   15    False
C  Rakesh   45    False
D  Mukesh   85     True

# Renaming Columns In data Frame

In [23]:
freind_df.rename(columns={'Name':'Friends_Name', 'Age':'Freinds_Age','Insured':'Insurance'})

  Friends_Name  Freinds_Age  Insurance
A       Rajeev           25       True
B        Rahul           15      False
C       Rakesh           45      False
D       Mukesh           85       True

In [26]:
freind_df.rename(columns={'Name':'Friends_Name', 'Age':'Freinds_Age','Insured':'Insurance'}, inplace=True)

In [27]:
freind_df

  Friends_Name  Freinds_Age  Insurance
A       Rajeev           25       True
B        Rahul           15      False
C       Rakesh           45      False
D       Mukesh           85       True

# Reading data from csv

In [28]:
ins_data = pd.read_csv("C:\Data Analytics\Python\Pandas\insurance.csv")
ins_data.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86