In [1]:
import pandas as pd

# Chapter 3 | Data Selection & Filtering

In [11]:
ins_data.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

# Selecting a Single Column

In [13]:
ins_data['sex'].head()

0    female
1      male
2      male
3      male
4      male
Name: sex, dtype: object

# Selecting Multiple Columns

In [18]:
ins_data[['sex','age','expenses']]

         sex  age  expenses
0     female   19  16884.92
1       male   18   1725.55
2       male   28   4449.46
3       male   33  21984.47
4       male   32   3866.86
...      ...  ...       ...
1333    male   50  10600.55
1334  female   18   2205.98
1335  female   18   1629.83
1336  female   21   2007.95
1337  female   61  29141.36

[1338 rows x 3 columns]

# Selecting Rows by Index Label —

# ➡️ What is loc[]?
# Label-based selection
# You can select one row, multiple rows, or rows + columns by their index label (like 'A', 'B', 'C' here).

In [19]:
ins_data.index

RangeIndex(start=0, stop=1338, step=1)

In [21]:
ins_data.loc[[400,450,500,550],['age','smoker']]

     age smoker
400   51     no
450   39     no
500   29    yes
550   63     no

# ✅ 4️⃣ Selecting Rows by Index Position — iloc[]
# ➡️ What is iloc[]?
# Position-based selection
# Uses integer positions (like 0, 1, 2, 3) to pick rows and columns.

In [22]:
ins_data.iloc[[100,101],[1,2]]

        sex   bmi
100  female  31.6
101    male  25.5

# ✅ 5️⃣ Filtering Rows Based on a Condition
# ➡️ Why Filter?
# Sometimes you need only the rows that match a rule (like "age greater than 40")

In [30]:
ins_data[ins_data['sex']=='male']

      age   sex   bmi  children smoker     region  expenses
1      18  male  33.8         1     no  southeast   1725.55
2      28  male  33.0         3     no  southeast   4449.46
3      33  male  22.7         0     no  northwest  21984.47
4      32  male  28.9         0     no  northwest   3866.86
8      37  male  29.8         2     no  northeast   6406.41
...   ...   ...   ...       ...    ...        ...       ...
1324   31  male  25.9         1     no  northwest   4239.89
1325   61  male  33.5         0     no  northeast  13143.34
1327   51  male  30.0         1     no  southeast   9377.90
1329   52  male  38.6         2     no  southwest  10325.21
1333   50  male  31.0         3     no  northwest  10600.55

[676 rows x 7 columns]

In [36]:
ins_data[(ins_data['age']>35) & (ins_data['smoker']=='yes')]

      age     sex   bmi  children smoker     region  expenses
11     62  female  26.3         0    yes  southeast  27808.73
39     60    male  39.9         0    yes  southwest  48173.36
49     36    male  35.2         1    yes  southeast  38709.18
52     48    male  28.0         1    yes  southwest  23568.27
53     36    male  34.4         0    yes  southeast  37742.58
...   ...     ...   ...       ...    ...        ...       ...
1303   43    male  27.8         0    yes  southwest  37829.72
1304   42    male  24.6         2    yes  northeast  21259.38
1321   62    male  26.7         0    yes  northeast  28101.33
1323   42  female  40.4         2    yes  southeast  43896.38
1337   61  female  29.1         0    yes  northwest  29141.36

[153 rows x 7 columns]

# ✅ 6️⃣ Selecting Specific Cells (Rows + Columns Together)
# You can select a single value by combining:
# loc[row_label, column_label]
# iloc[row_position, column_position]

In [40]:
ins_data.loc[400,'bmi']

np.float64(20.6)

In [45]:
ins_data.iloc[400,2]

np.float64(20.6)